### ISSUE TITLE
スライドバナーを実装する

### ISSUE THREAD

**Issue by arith-y-ono** [arith-alexander/docker#2]
スライドバナーを実装する
最低３つバナーがありスライドするようにする

バナーの遷移は固定とする（秒数は要相談）
5秒を目安とする

**Comment by arith-y-ono** [comment]
画像サイズを決める→確認

**Comment by arith-y-ono** [comment]
スライド速度はデフォルト、なければ1秒で流れる。
アニメーションはデフォルト

その他は都度確認する

**Comment by arith-alexander** [comment]
着手します

**Comment by arith-y-ono** [comment]
https://github.com/arith-alexander/docker/pull/29 対応済み
