### ISSUE TITLE
レッスン、ストーリー、ガチャボタンを実装する

### ISSUE THREAD

**Issue by arith-y-ono** [arith-alexander/docker#4]
レッスン、ストーリー、ガチャボタンを実装する
ボタンを押せる
画面遷移ができること

最低限の実装のため画像などはサンプルとなる。
ボタンについても文字とする

**Comment by arith-y-ono** [comment]
飛ぶ先はblankで作成すること

**Comment by arith-y-ono** [comment]
サイズは実装時に確認

**Comment by arith-alexander** [comment]
https://github.com/arith-alexander/docker/pull/22 にて対応済み
