### ISSUE TITLE
menuボタンを実装する

### ISSUE THREAD

**Issue by arith-y-ono** [arith-alexander/docker#5]
menuボタンを実装する。
menuボタンについてはマイページにポップアップの形で表示される

✖︎ボタンを押すことで消える
中身のアセットについてはサンプルとして
３かける３のものを表示させる

**Comment by arith-y-ono** [comment]
最初はデフォルト状態で実装する。
ヘッダーは必要かは実装時に確認する

**Comment by arith-alexander** [comment]
https://github.com/arith-alexander/docker/pull/26 にて対応済み
