### ISSUE TITLE
タップした時にキャラクターがlive2dで動くようにする

### ISSUE THREAD

**Issue by arith-y-ono** [arith-alexander/docker#8]
# 前提issue: https://github.com/arith-alexander/docker/issues/7

タップした時にキャラクターがlive2dで動くようにする

**Comment by arith-y-ono** [comment]
モーションについてはサンプルに存在するものをそのまま流用する

**Comment by arith-y-ono** [comment]
デフォルトのものはおそらくタップ時に音声が再生されるので音声を削除する

**Comment by arith-y-ono** [comment]
タップ時にボイスが流れること

**Comment by arith-alexander** [comment]
着手します

**Comment by arith-y-ono** [comment]
対応ずみ
